export const mockIncidentReports = [
    {
        _id: 1,
        category: "Crime-Related Incidents",
        subCategory: "Theft/Burglary",
        date: "2024-03-15",
        time: "14:30",
        location: "123 Main St, Barangay Centro",
        description: "Laptop stolen from parked car",
        reporterName: "John Doe",
        reporterContact: "09123456789",
        status: "pending",
        barangay: "Barangay Centro",
    },
    {
        _id: 2,
        category: "Community Disturbances",
        subCategory: "Noise Complaints",
        date: "2024-03-14",
        time: "22:00",
        location: "456 Elm St, Barangay Centro",
        description: "Loud party causing disturbance to neighbors",
        reporterName: "Jane Smith",
        reporterContact: "09187654321",
        status: "resolved",
        barangay: "Barangay Centro",
    },
    {
        _id: 3,
        category: "Environmental & Health Concerns",
        subCategory: "Garbage Dumping",
        date: "2024-03-13",
        time: "09:15",
        location: "789 Oak Ave, Barangay Centro",
        description: "Illegal dumping of construction materials",
        reporterName: "Mike Wilson",
        reporterContact: "09198765432",
        status: "pending",
        barangay: "Barangay Centro",
    },
    {
        _id: 4,
        category: "Traffic & Road Issues",
        subCategory: "Illegal Parking",
        date: "2024-03-12",
        time: "16:45",
        location: "101 Pine St, Barangay Centro",
        description: "Multiple vehicles blocking the road",
        reporterName: "Sarah Johnson",
        reporterContact: "09123456788",
        status: "resolved",
        barangay: "Barangay Centro",
    },
];

export const mockDocumentRequests = [
    {
        id: 1,
        type: "Barangay Clearance",
        requestDate: "2023-06-01",
        residentName: "John Doe",
        purpose: "Job Application",
        status: "Pending",
    },
    {
        id: 2,
        type: "Barangay Indigency",
        requestDate: "2023-06-02",
        residentName: "Jane Smith",
        purpose: "Medical Assistance",
        status: "Approved",
    },
    {
        id: 3,
        type: "Cedula",
        requestDate: "2023-06-03",
        residentName: "Bob Johnson",
        purpose: "Business Permit",
        status: "Completed",
    },
    {
        id: 4,
        type: "Barangay Business Clearance",
        requestDate: "2023-06-04",
        residentName: "Alice Brown",
        purpose: "New Business Registration",
        status: "Pending",
    },
    // Add more mock data as needed
];

export const mockResidents = [
    {
        id: 1,
        name: "John Doe",
        age: 35,
        address: "123 Main St, Barangay Centro",
        contactNumber: "123-456-7890",
        occupation: "Teacher",
        familyMembers: 4,
        dateRegistered: "2022-01-15",
        profileImage: "/placeholder.svg?height=100&width=100",
    },
    {
        id: 2,
        name: "Jane Smith",
        age: 28,
        address: "456 Elm St, Barangay Norte",
        contactNumber: "987-654-3210",
        occupation: "Nurse",
        familyMembers: 2,
        dateRegistered: "2022-03-22",
        profileImage: "/placeholder.svg?height=100&width=100",
    },
    {
        id: 3,
        name: "Bob Johnson",
        age: 45,
        address: "789 Oak Ave, Barangay Sur",
        contactNumber: "456-789-0123",
        occupation: "Business Owner",
        familyMembers: 5,
        dateRegistered: "2021-11-30",
        profileImage: "/placeholder.svg?height=100&width=100",
    },
    {
        id: 4,
        name: "Alice Brown",
        age: 52,
        address: "101 Pine Rd, Barangay Este",
        contactNumber: "789-012-3456",
        occupation: "Accountant",
        familyMembers: 3,
        dateRegistered: "2022-05-10",
        profileImage: "/placeholder.svg?height=100&width=100",
    },
    {
        id: 5,
        name: "Charlie Davis",
        age: 30,
        address: "202 Cedar Ln, Barangay Oeste",
        contactNumber: "321-654-9870",
        occupation: "Engineer",
        familyMembers: 1,
        dateRegistered: "2022-07-05",
        profileImage: "/placeholder.svg?height=100&width=100",
    },
];

// Mock data for testing
export const mockRequests = [
    {
        id: 1,
        documentType: "Barangay Clearance",
        status: "pending",
        createdAt: "2024-03-15",
        purpose: "Job Application",
    },
    {
        id: 2,
        documentType: "Barangay Indigency",
        status: "approved",
        createdAt: "2024-03-10",
        purpose: "Medical Assistance",
    },
    {
        id: 3,
        documentType: "Cedula",
        status: "rejected",
        createdAt: "2024-03-05",
        purpose: "Business Permit",
    },
    {
        id: 4,
        documentType: "Barangay Business Clearance",
        status: "approved",
        createdAt: "2024-03-01",
        purpose: "Business Registration",
    },
];

export const mockBlotterReports = [
    {
        _id: 1,
        complainantName: "John Doe",
        complainantContact: "09123456789",
        complainantAddress: "123 Main St, Barangay Centro",
        respondentName: "Richard Roe",
        respondentAddress: "456 Elm St, Barangay Centro",
        incidentDate: "2024-03-15",
        incidentTime: "14:30",
        incidentLocation: "Local Market, Barangay Centro",
        incidentType: "Theft",
        narrative: "Suspect took victim's wallet containing cash and important documents",
        status: "pending",
        actionRequested: "Mediation",
        dateReported: "2024-03-15",
    },
    {
        _id: 2,
        complainantName: "Maria Santos",
        complainantContact: "09187654321",
        complainantAddress: "789 Oak St, Barangay Centro",
        respondentName: "Juan Dela Cruz",
        respondentAddress: "101 Pine St, Barangay Centro",
        incidentDate: "2024-03-14",
        incidentTime: "20:00",
        incidentLocation: "Residential Area, Barangay Centro",
        incidentType: "Noise Disturbance",
        narrative: "Respondent's karaoke session exceeding quiet hours",
        status: "resolved",
        actionRequested: "Barangay Intervention",
        dateReported: "2024-03-14",
    },
    {
        _id: 3,
        complainantName: "Pedro Garcia",
        complainantContact: "09198765432",
        complainantAddress: "202 Cedar St, Barangay Centro",
        respondentName: "Ana Cruz",
        respondentAddress: "303 Maple St, Barangay Centro",
        incidentDate: "2024-03-13",
        incidentTime: "10:00",
        incidentLocation: "Property Line, Barangay Centro",
        incidentType: "Property Dispute",
        narrative: "Dispute over fence placement between neighboring properties",
        status: "ongoing",
        actionRequested: "Mediation",
        dateReported: "2024-03-13",
    },
];

export const mockLogs = [
    {
        id: 1,
        timestamp: "2023-06-25T10:30:00Z",
        type: "User Activity",
        user: "john.doe",
        action: "Login",
        details: "User logged in successfully",
    },
    {
        id: 2,
        timestamp: "2023-06-25T11:15:00Z",
        type: "Resident Record",
        user: "jane.smith",
        action: "Update",
        details: "Updated address for resident ID: 12345",
    },
    {
        id: 3,
        timestamp: "2023-06-25T12:00:00Z",
        type: "Barangay Clearance",
        user: "admin.user",
        action: "Issue",
        details: "Issued clearance for resident ID: 67890",
    },
    {
        id: 4,
        timestamp: "2023-06-25T13:30:00Z",
        type: "Incident Report",
        user: "officer.johnson",
        action: "Create",
        details: "Created new incident report: Noise complaint",
    },
    {
        id: 5,
        timestamp: "2023-06-25T14:45:00Z",
        type: "Audit",
        user: "system",
        action: "Backup",
        details: "System backup completed successfully",
    },
    // Add more mock data as needed
];

export const mockUsers = [
    {
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        role: "Resident",
        address: "123 Main St, Barangay Centro",
        phoneNumber: "+63 912 345 6789",
        dateRegistered: "2023-01-15",
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        role: "Barangay Official",
        address: "456 Elm St, Barangay Norte",
        phoneNumber: "+63 923 456 7890",
        dateRegistered: "2023-02-20",
    },
    {
        id: 3,
        name: "Mike Johnson",
        email: "mike.johnson@example.com",
        role: "Secretary",
        address: "789 Oak Ave, Barangay Sur",
        phoneNumber: "+63 934 567 8901",
        dateRegistered: "2023-03-10",
    },
    {
        id: 4,
        name: "Sarah Lee",
        email: "sarah.lee@example.com",
        role: "Resident",
        address: "101 Pine Rd, Barangay Este",
        phoneNumber: "+63 945 678 9012",
        dateRegistered: "2023-04-05",
    },
    {
        id: 5,
        name: "David Chen",
        email: "david.chen@example.com",
        role: "Admin",
        address: "202 Cedar Ln, Barangay Oeste",
        phoneNumber: "+63 956 789 0123",
        dateRegistered: "2023-05-01",
    },
];
